build editor, notecard component
mason-nguyen-goldenowl/excer-clone-google-keep pull request #1
Opened 2022-01-05 11:24 UTC by mason-nguyen-goldenowl

**Task/Ticket:**
  Build Ediorm, NoteCard component
**Description:**

- Build UI and feature for Editor component

- Build UI for note card

Screenshots:

[https://drive.google.com/file/d/1a560PBFHWKZqH1nRcJ3h2_fQIG8oHpJA/view?usp=sharing](url)

2022-01-15 07:27 UTC, jun-nguyen-goldenowl requested changes

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/body/Body.js
> +    });
DO NOT use array's index as `key`

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/body/Body.js
> +import { useSelector } from "react-redux";
```suggestion
import { useSelector } from "react-redux";

import SideMenu from "../sideMenu/SideMenu";
import NoteText from "../noteText/NoteText";
import NoteCard from "../noteCard/NoteCard";
import "./Body.scss";
```

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/editor/Editor.js
> +import { useDispatch } from "react-redux";
basically, we have 3 types of imports:
1. libraries/packages imports: `moment`, `redux`, `react`, ...
2. project's modules imports: `components`, `services`, ...
3. relative imports: it's better to have only `../../file` or `./file` or `../file`

one more thing, any imports from `react` should be placed on top of other imports in `libraries/packages` section

so that, imports for libraries/packages should be placed on top of others.
like this
```jsx
import React, { useRef, useState } from "react";
import moment from "moment";
import { useDispatch } from "react-redux";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

import reminder from "../../asset/editorIcon/reminder.svg";
import pin from "../../asset/editorIcon/pin.svg";
import colab from "../../asset/editorIcon/colab.svg";
import background from "../../asset/editorIcon/background.svg";
import image from "../../asset/editorIcon/image.svg";
import archive from "../../asset/editorIcon/archive.svg";
import more from "../../asset/editorIcon/more.svg";
import undo from "../../asset/editorIcon/undo.svg";
import time from "../../asset/editorIcon/time.svg";
import "./Editor.scss";

```

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/noteCard/NoteCard.js
> +export default function NoteCard(props) {
```suggestion
import "./NoteCard.scss";

export default function NoteCard(props) {
```

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/noteText/NoteText.js
> +        {/* <input className={`show__input ${showClass}`} placeholder="Take a note..." /> */}
remove un-used code OR leave a TODO comment for explanation

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/components/noteText/NoteText.scss
> +  &__show {
It's better to have a blank line between stylings of current block and its selectors

```suggestion
  max-width: 600px;
  
  &__show {
```

2022-01-15 07:27 UTC, jun-nguyen-goldenowl commented on src/redux/type/NoteType.js
> +export const ADDNOTE = "ADDNOTE";
if letters are all UPPER CASE, we can add `_` as word separator 

```suggestion
export const ADD_NOTE = "ADD_NOTE";
```

code is now more readable

2022-01-18 06:24 UTC, jun-nguyen-goldenowl requested changes

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/editor/Editor.js
> +  const text = useRef("");
those reference variables should have postfix `Ref` for better code reading/recognization

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/menu/Menu.js
> +import { useDispatch } from "react-redux";
your eslint did not fire any errors/warnings for case of there's more than one `import` for things in same module, did it?

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/menu/Menu.js
> +import { useDispatch } from "react-redux";
```suggestion
import { useSelector, useDispatch } from "react-redux";
```

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/noteCard/NoteCard.scss
> +.noteCard {
```suggestion
@use "../../scss/" as *;

.noteCard {
```

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/noteCard/NoteCard.scss
> +    left: 0;
does it work as expected when we have only 1 trailing point (`left`)?

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/noteText/NoteText.js
> +        <div className={`editor-wrap ${showClass}`}>
https://www.npmjs.com/package/classnames check it out

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/sideMenu/SideMenu.js
> +            </svg>
define this one as a asset in src/assets/icons. Then, try to use the supported SVG imports https://dev.to/deadlybyte/import-svg-directly-as-a-reactcomponent-adk

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/sideMenu/SideMenu.js
> +            </svg>
this too

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/sideMenu/SideMenu.js
> +            </svg>
this too

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/sideMenu/SideMenu.js
> +            </svg>
this too

2022-01-18 06:24 UTC, jun-nguyen-goldenowl commented on src/components/sideMenu/SideMenu.js
> +            </svg>
this too

2022-01-18 09:14 UTC, mason-nguyen-goldenowl commented on src/components/noteText/NoteText.js
> +        <div className={`editor-wrap ${showClass}`}>
I have fixed this at  Feature/Classify-by-labels PR
I used NoteText component like Modal component to open Editor component

2022-01-20 06:21 UTC, jun-nguyen-goldenowl approved these changes

2022-01-20 06:22 UTC, jun-nguyen-goldenowl commented
@mason-nguyen-goldenowl please go merge this one

2022-01-20 06:25 UTC, merged